### ISSUE TITLE
@conda-forge-admin, please add user @conda-forge/sphinx

### ISSUE THREAD

**Issue by AA-Turner** [conda-forge/sphinxcontrib-ansi-feedstock#1]

**Comment by awvwgk** [comment]
Hi @AA-Turner, is there any particular reason for having more maintainers on this feedstock? Don't get me wrong I am happy for all helping hands.

**Comment by AA-Turner** [comment]
Primarily I'm going through ``conda-forge`` and adding the ``sphinx`` team as maintainers to the Sphinx related packages -- this is done with the ``R`` ecosystem and I thought seemed a sensible idea -- cross-pollinating the maintainers of the various Sphinx-affiliated packages on CF.
